add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_68e8b08330be8',
	'title' => 'Flexible Content Sections',
	'fields' => array(
		array(
			'key' => 'field_68e8b084f99a5',
			'label' => 'Flex content',
			'name' => 'flex_content',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_68f724726c432' => array(
					'key' => 'layout_68f724726c432',
					'name' => 'hero_banner',
					'label' => 'Hero banner',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_69084a431daf4',
							'label' => 'Section ID',
							'name' => 'section_id',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_68f724bb6c434',
							'label' => 'Intro line',
							'name' => 'intro_line',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_68f724c76c435',
							'label' => 'Headline',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'rows' => '',
							'placeholder' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_68f724d66c436',
							'label' => 'Tagline',
							'name' => 'tagline',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'rows' => '',
							'placeholder' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_68f724e36c437',
							'label' => 'Primary Button',
							'name' => 'primary_button',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'allow_in_bindings' => 0,
						),
						array(
							'key' => 'field_68f724f26c438',
							'label' => 'Secondary Button',
							'name' => 'secondary_button',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'allow_in_bindings' => 0,
						),
						array(
							'key' => 'field_68f725026c439',
							'label' => 'Background Image',
							'name' => 'background_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_69084a5c1daf5',
							'label' => 'Background Color',
							'name' => 'background_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-black' => 'Black',
								'bg-dark' => 'Dark',
								'bg-gray-100' => 'Gray 100',
								'bg-gray-150' => 'Gray 150',
								'bg-gray-200' => 'Gray 200',
								'bg-gray-300' => 'Gray 300',
								'bg-gray-400' => 'Gray 400',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_69084a801daf6',
							'label' => 'Font Color',
							'name' => 'font_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-black' => 'Black',
								'text-dark' => 'Dark',
								'text-gray-100' => 'Gray 100',
								'text-gray-150' => 'Gray 150',
								'text-gray-200' => 'Gray 200',
								'text-gray-300' => 'Gray 300',
								'text-gray-400' => 'Gray 400',
								'text-orange' => 'Orange',
							),
							'default_value' => 'text-white',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68e8b0c67ab7a' => array(
					'key' => 'layout_68e8b0c67ab7a',
					'name' => 'logo_slider',
					'label' => 'Logo slider',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68f86a672579c',
							'label' => 'Section ID',
							'name' => 'section_id',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_69084cfe8ad63',
							'label' => 'Background Image',
							'name' => 'background_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_68f86a952579e',
							'label' => 'Background Color',
							'name' => 'background_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-black' => 'Black',
								'bg-dark' => 'Dark',
								'bg-gray-100' => 'Gray 100',
								'bg-gray-150' => 'Gray 150',
								'bg-gray-200' => 'Gray 200',
								'bg-gray-300' => 'Gray 300',
								'bg-gray-400' => 'Gray 400',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_69084d128ad64',
							'label' => 'Font Color',
							'name' => 'font_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-black' => 'Black',
								'text-dark' => 'Dark',
								'text-gray-100' => 'Gray 100',
								'text-gray-150' => 'Gray 150',
								'text-gray-200' => 'Gray 200',
								'text-gray-300' => 'Gray 300',
								'text-gray-400' => 'Gray 400',
								'text-orange' => 'Orange',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_69080fbe1e30e',
							'label' => 'Rows',
							'name' => 'rows',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => '1 Row',
								2 => '2 Rows',
								3 => '3 Rows',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_68f86aa32579f',
							'label' => 'Logos',
							'name' => 'logos',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Logo',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_68f86ab3257a0',
									'label' => 'Logo Image',
									'name' => 'logo_image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_68f86aa32579f',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_full_width_block_hover' => array(
					'key' => 'layout_full_width_block_hover',
					'name' => 'full_width_block_hover',
					'label' => 'Full width block hover',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68f8886ca1598',
							'label' => 'Section Id',
							'name' => 'section_id',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_690ae917cf4de',
							'label' => 'Section Title',
							'name' => 'section_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_690ae926cf4df',
							'label' => 'Section Description',
							'name' => 'section_description',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'rows' => '',
							'placeholder' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_69084849bf12c',
							'label' => 'Font Color',
							'name' => 'font_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-black' => 'Black',
								'text-dark' => 'Dark',
								'text-gray-100' => 'Gray 100',
								'text-gray-150' => 'Gray 150',
								'text-gray-200' => 'Gray 200',
								'text-gray-300' => 'Gray 300',
								'text-gray-400' => 'Gray 400',
								'text-orange' => 'Orange',
							),
							'default_value' => 'text-white',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_69084811bf12a',
							'label' => 'Background Color',
							'name' => 'background_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-black' => 'Black',
								'bg-dark' => 'Dark',
								'bg-gray-100' => 'Gray 100',
								'bg-gray-150' => 'Gray 150',
								'bg-gray-200' => 'Gray 200',
								'bg-gray-300' => 'Gray 300',
								'bg-gray-400' => 'Gray 400',
							),
							'default_value' => 'bg-dark',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_69084834bf12b',
							'label' => 'Background Image',
							'name' => 'background_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_690aeb6f98cb7',
							'label' => 'Rows',
							'name' => 'rows',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => '1',
								2 => '2',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_690af071b4583',
							'label' => 'Source',
							'name' => 'source',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'post_type' => 'From Services',
								'manual' => 'Manual',
							),
							'default_value' => 'post_type',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_68f88885a1599',
							'label' => 'Blocks',
							'name' => 'blocks',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_690af071b4583',
										'operator' => '==',
										'value' => 'manual',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'row',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_68f888a2a159a',
									'label' => 'Background Image',
									'name' => 'background_image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_68f88885a1599',
								),
								array(
									'key' => 'field_68f888b7a159b',
									'label' => 'Icon',
									'name' => 'icon',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_68f88885a1599',
								),
								array(
									'key' => 'field_68f888c7a159c',
									'label' => 'Title',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_68f88885a1599',
								),
								array(
									'key' => 'field_68f888d3a159d',
									'label' => 'Short Text',
									'name' => 'short_text',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_68f88885a1599',
								),
								array(
									'key' => 'field_68f888dea159e',
									'label' => 'Long Text',
									'name' => 'long_text',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'rows' => '',
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_68f88885a1599',
								),
								array(
									'key' => 'field_68f888eda159f',
									'label' => 'Button',
									'name' => 'button',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'allow_in_bindings' => 0,
									'parent_repeater' => 'field_68f88885a1599',
								),
								array(
									'key' => 'field_6908549ea50df',
									'label' => 'Page Link',
									'name' => 'page_link',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'allow_in_bindings' => 0,
									'parent_repeater' => 'field_68f88885a1599',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_testimonial_card_slider' => array(
					'key' => 'layout_testimonial_card_slider',
					'name' => 'testimonial_card_slider',
					'label' => 'Testimonial card slider',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_69084d86b978d',
							'label' => 'Section ID',
							'name' => 'section_id',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_69084d98b978e',
							'label' => 'Background Color',
							'name' => 'background_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-black' => 'Black',
								'bg-dark' => 'Dark',
								'bg-gray-100' => 'Gray 100',
								'bg-gray-150' => 'Gray 150',
								'bg-gray-200' => 'Gray 200',
								'bg-gray-300' => 'Gray 300',
								'bg-gray-400' => 'Gray 400',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_69084dcab978f',
							'label' => 'Font Color',
							'name' => 'font_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-black' => 'Black',
								'text-dark' => 'Dark',
								'text-gray-100' => 'Gray 100',
								'text-gray-150' => 'Gray 150',
								'text-gray-200' => 'Gray 200',
								'text-gray-300' => 'Gray 300',
								'text-gray-400' => 'Gray 400',
								'text-orange' => 'Orange',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_690052bea20bd',
							'label' => 'Section Title',
							'name' => 'section_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_690850c5cfc96' => array(
					'key' => 'layout_690850c5cfc96',
					'name' => 'case_study_card_slider',
					'label' => 'Case Study Card Slider',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_690850c5cfc97',
							'label' => 'Section ID',
							'name' => 'section_id',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6909696c0f763',
							'label' => 'Background Image',
							'name' => 'background_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_690850c5cfc98',
							'label' => 'Background Color',
							'name' => 'background_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-black' => 'Black',
								'bg-dark' => 'Dark',
								'bg-gray-100' => 'Gray 100',
								'bg-gray-150' => 'Gray 150',
								'bg-gray-200' => 'Gray 200',
								'bg-gray-300' => 'Gray 300',
								'bg-gray-400' => 'Gray 400',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_690850c5cfc99',
							'label' => 'Font Color',
							'name' => 'font_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-black' => 'Black',
								'text-dark' => 'Dark',
								'text-gray-100' => 'Gray 100',
								'text-gray-150' => 'Gray 150',
								'text-gray-200' => 'Gray 200',
								'text-gray-300' => 'Gray 300',
								'text-gray-400' => 'Gray 400',
								'text-orange' => 'Orange',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_690850c5cfc9a',
							'label' => 'Section Title',
							'name' => 'section_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_info_card_blocks' => array(
					'key' => 'layout_info_card_blocks',
					'name' => 'info_card_blocks',
					'label' => 'Info card blocks',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6900671ca5f55',
							'label' => 'Section ID',
							'name' => 'section_id',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_69084b4ef03c2',
							'label' => 'Background Color',
							'name' => 'background_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-black' => 'Black',
								'bg-dark' => 'Dark',
								'bg-gray-100' => 'Gray 100',
								'bg-gray-150' => 'Gray 150',
								'bg-gray-200' => 'Gray 200',
								'bg-gray-300' => 'Gray 300',
								'bg-gray-400' => 'Gray 400',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_69084b83f03c3',
							'label' => 'Font Color',
							'name' => 'font_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-black' => 'Black',
								'text-dark' => 'Dark',
								'text-gray-100' => 'Gray 100',
								'text-gray-150' => 'Gray 150',
								'text-gray-200' => 'Gray 200',
								'text-gray-300' => 'Gray 300',
								'text-gray-400' => 'Gray 400',
								'text-orange' => 'Orange',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_6900673f52e7e',
							'label' => 'Title',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6900674652e7f',
							'label' => 'Description',
							'name' => 'description',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'rows' => '',
							'placeholder' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_6900675352e80',
							'label' => 'Background Image',
							'name' => 'background_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_6900676052e81',
							'label' => 'Blocks',
							'name' => 'blocks',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_6900676f52e82',
									'label' => 'Block background image',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_6900676052e81',
								),
								array(
									'key' => 'field_6900678252e83',
									'label' => 'Heading',
									'name' => 'heading',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_6900676052e81',
								),
								array(
									'key' => 'field_6900679752e84',
									'label' => 'Text',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'rows' => '',
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_6900676052e81',
								),
								array(
									'key' => 'field_690ad20b42a48',
									'label' => 'Block link',
									'name' => 'block_link',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'allow_in_bindings' => 0,
									'parent_repeater' => 'field_6900676052e81',
								),
							),
						),
						array(
							'key' => 'field_690067a752e85',
							'label' => 'Button',
							'name' => 'button',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'allow_in_bindings' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_icon_column_section' => array(
					'key' => 'layout_icon_column_section',
					'name' => 'icon_column_section',
					'label' => 'Icon column section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_69084acb21bb5',
							'label' => 'Section ID',
							'name' => 'section_id',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6901b61df7dcf',
							'label' => 'Background Color',
							'name' => 'background_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-black' => 'Black',
								'bg-dark' => 'Dark',
								'bg-orange' => 'Orange',
								'bg-gray-100' => 'Gray 100',
								'bg-gray-200' => 'Gray 200',
								'bg-gray-300' => 'Gray 300',
								'bg-gray-400' => 'Gray 400',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_69084ae221bb6',
							'label' => 'Font Color',
							'name' => 'font_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-black' => 'Black',
								'text-dark' => 'Dark',
								'text-gray-100' => 'Gray 100',
								'text-gray-150' => 'Gray 150',
								'text-gray-200' => 'Gray 200',
								'text-gray-300' => 'Gray 300',
								'text-gray-400' => 'Gray 400',
								'text-orange' => 'Orange',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_6901b3101d420',
							'label' => 'Section Title',
							'name' => 'section_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6901b31b1d421',
							'label' => 'Section Description',
							'name' => 'section_description',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => false,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'default_value' => '',
							'delay' => 0,
						),
						array(
							'key' => 'field_6901b32a1d422',
							'label' => 'Block Wrapper Title',
							'name' => 'block_wrapper_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6908162d23ee3',
							'label' => 'Content Source',
							'name' => 'content_source',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'sectors' => 'Use Sectors (Auto)',
								'manual' => 'Manual Blocks',
							),
							'default_value' => 'sectors',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_6901b3361d423',
							'label' => 'Blocks',
							'name' => 'blocks',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6908162d23ee3',
										'operator' => '==',
										'value' => 'manual',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add block',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_6901b34d1d424',
									'label' => 'Icon',
									'name' => 'icon',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_6901b3361d423',
								),
								array(
									'key' => 'field_6901b3591d425',
									'label' => 'Block Title',
									'name' => 'block_title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_6901b3361d423',
								),
								array(
									'key' => 'field_6901b3631d426',
									'label' => 'Block Description',
									'name' => 'block_description',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'allow_in_bindings' => 0,
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
									'parent_repeater' => 'field_6901b3361d423',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_full_width_text_section' => array(
					'key' => 'layout_full_width_text_section',
					'name' => 'full_width_text_section',
					'label' => 'Full width text section',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_grid_section' => array(
					'key' => 'layout_grid_section',
					'name' => 'grid_section',
					'label' => 'Grid section',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_690849439ae49',
							'label' => 'Background Color',
							'name' => 'background_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-black' => 'Black',
								'bg-dark' => 'Dark',
								'bg-gray-100' => 'Gray 100',
								'bg-gray-150' => 'Gray 150',
								'bg-gray-200' => 'Gray 200',
								'bg-gray-300' => 'Gray 300',
								'bg-gray-400' => 'Gray 400',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_690849799ae4a',
							'label' => 'Background Image',
							'name' => 'background_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_690849929ae4b',
							'label' => 'Font Color',
							'name' => 'font_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-black' => 'Black',
								'text-dark' => 'Dark',
								'text-gray-100' => 'Gray 100',
								'text-gray-150' => 'Gray 150',
								'text-gray-200' => 'Gray 200',
								'text-gray-300' => 'Gray 300',
								'text-gray-400' => 'Gray 400',
								'text-orange' => 'Orange',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_690418799de08',
							'label' => 'Section Title',
							'name' => 'section_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_690418839de09',
							'label' => 'Section Description',
							'name' => 'section_description',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'rows' => '',
							'placeholder' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_69096bb25ff8a',
							'label' => 'Content Source',
							'name' => 'content_source',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Testimonial' => 'Testimonial',
								'Manual' => 'Manual',
							),
							'default_value' => 'Testimonial',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_690418929de0a',
							'label' => 'Grid Items',
							'name' => 'grid_items',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_69096bb25ff8a',
										'operator' => '==',
										'value' => 'Manual',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_690418a39de0b',
									'label' => 'Title',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_690418929de0a',
								),
								array(
									'key' => 'field_690418ae9de0c',
									'label' => 'Size',
									'name' => 'size',
									'aria-label' => '',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'small' => 'small',
										'half' => 'half',
										'tall' => 'tall',
										'wide' => 'wide',
									),
									'default_value' => 'small',
									'return_format' => 'value',
									'multiple' => 0,
									'allow_null' => 0,
									'allow_in_bindings' => 0,
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'create_options' => 0,
									'save_options' => 0,
									'parent_repeater' => 'field_690418929de0a',
								),
								array(
									'key' => 'field_690418dc9de0d',
									'label' => 'Video',
									'name' => 'video',
									'aria-label' => '',
									'type' => 'file',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_size' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'parent_repeater' => 'field_690418929de0a',
								),
								array(
									'key' => 'field_690418ea9de0e',
									'label' => 'Logo',
									'name' => 'logo',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_690418929de0a',
								),
								array(
									'key' => 'field_69083dad22afe',
									'label' => 'Url',
									'name' => 'post_url',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'allow_in_bindings' => 0,
									'parent_repeater' => 'field_690418929de0a',
								),
								array(
									'key' => 'field_69083fc58cd2d',
									'label' => 'Image Fallback',
									'name' => 'image_fallback',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_690418dc9de0d',
												'operator' => '==empty',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_690418929de0a',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_row_text_column' => array(
					'key' => 'layout_row_text_column',
					'name' => 'row_text_column',
					'label' => 'Row text column',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_69042c4507018' => array(
					'key' => 'layout_69042c4507018',
					'name' => 'leadership_fullwidth_automatic_slider',
					'label' => 'Leadership fullwidth automatic slider',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_69084c28f8e18',
							'label' => 'Section ID',
							'name' => 'section_id',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_69084c6d8ad62',
							'label' => 'Background Image',
							'name' => 'background_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_69042c4507019',
							'label' => 'Background Color',
							'name' => 'background_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-black' => 'Black',
								'bg-dark' => 'Dark',
								'bg-orange' => 'Orange',
								'bg-gray-100' => 'Gray 100',
								'bg-gray-200' => 'Gray 200',
								'bg-gray-300' => 'Gray 300',
								'bg-gray-400' => 'Gray 400',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_69084c3af8e19',
							'label' => 'Font Color',
							'name' => 'font_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-black' => 'Black',
								'text-dark' => 'Dark',
								'text-gray-100' => 'Gray 100',
								'text-gray-150' => 'Gray 150',
								'text-gray-200' => 'Gray 200',
								'text-gray-300' => 'Gray 300',
								'text-gray-400' => 'Gray 400',
								'text-orange' => 'Orange',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_69042c450701a',
							'label' => 'Section Title',
							'name' => 'section_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_69042c450701b',
							'label' => 'Section Description',
							'name' => 'section_description',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 1,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_69042c450701c',
							'label' => 'Member Wrapper Title',
							'name' => 'member_wrapper_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_69042c450701d',
							'label' => 'Members',
							'name' => 'members',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add block',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_69042c450701e',
									'label' => 'Member',
									'name' => 'member',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'allow_in_bindings' => 0,
									'preview_size' => 'medium',
									'parent_repeater' => 'field_69042c450701d',
								),
								array(
									'key' => 'field_69042c450701f',
									'label' => 'Member Name',
									'name' => 'member_name',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_69042c450701d',
								),
								array(
									'key' => 'field_69042cac2c1f6',
									'label' => 'Member position',
									'name' => 'member_position',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'allow_in_bindings' => 0,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_69042c450701d',
								),
								array(
									'key' => 'field_69042c4507020',
									'label' => 'Member Description',
									'name' => 'member_description',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'allow_in_bindings' => 0,
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
									'parent_repeater' => 'field_69042c450701d',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_two_column_section' => array(
					'key' => 'layout_two_column_section',
					'name' => 'two_column_section',
					'label' => 'Two column section with form',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_69084eaf35649',
							'label' => 'Section ID',
							'name' => 'section_id',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_69084ec23564a',
							'label' => 'Background Color',
							'name' => 'background_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-black' => 'Black',
								'bg-dark' => 'Dark',
								'bg-gray-100' => 'Gray 100',
								'bg-gray-150' => 'Gray 150',
								'bg-gray-200' => 'Gray 200',
								'bg-gray-300' => 'Gray 300',
								'bg-gray-400' => 'Gray 400',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_690441be4b25b',
							'label' => 'Background Image',
							'name' => 'background_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_69084ee03564b',
							'label' => 'Font color',
							'name' => 'font_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-black' => 'Black',
								'text-dark' => 'Dark',
								'text-gray-100' => 'Gray 100',
								'text-gray-150' => 'Gray 150',
								'text-gray-200' => 'Gray 200',
								'text-gray-300' => 'Gray 300',
								'text-gray-400' => 'Gray 400',
								'text-orange' => 'Orange',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_690441cd4b25c',
							'label' => 'Section Title',
							'name' => 'section_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_690441d74b25d',
							'label' => 'Section Description',
							'name' => 'section_description',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_690441e74b25e',
							'label' => 'Left Content',
							'name' => 'left_content',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 0,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_690441f44b25f',
							'label' => 'Form Content',
							'name' => 'form_content',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_690442034b260',
							'label' => 'Reverse Columns',
							'name' => 'reverse_columns',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_news_and_media' => array(
					'key' => 'layout_news_and_media',
					'name' => 'news_and_media',
					'label' => 'News and media',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_690987ae950e9',
							'label' => 'Section ID',
							'name' => 'section_id',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_690987ba950ea',
							'label' => 'Background Color',
							'name' => 'background_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'bg-white' => 'White',
								'bg-black' => 'Black',
								'bg-dark' => 'Dark',
								'bg-gray-100' => 'Gray 100',
								'bg-gray-150' => 'Gray 150',
								'bg-gray-200' => 'Gray 200',
								'bg-gray-300' => 'Gray 300',
								'bg-gray-400' => 'Gray 400',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_690987d8950eb',
							'label' => 'Font Color',
							'name' => 'font_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-black' => 'Black',
								'text-dark' => 'Dark',
								'text-gray-100' => 'Gray 100',
								'text-gray-150' => 'Gray 150',
								'text-gray-200' => 'Gray 200',
								'text-gray-300' => 'Gray 300',
								'text-gray-400' => 'Gray 400',
								'text-orange' => 'Orange',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'create_options' => 0,
							'save_options' => 0,
						),
						array(
							'key' => 'field_690987f0950ec',
							'label' => 'Section Title',
							'name' => 'section_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_690987fd950ed',
							'label' => 'Podcast Embed',
							'name' => 'podcast_embed',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 0,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_icon_row_section' => array(
					'key' => 'layout_icon_row_section',
					'name' => 'icon_row_section',
					'label' => 'Icon row section',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_video_section' => array(
					'key' => 'layout_video_section',
					'name' => 'video_section',
					'label' => 'Video section',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_full_width_with_three_column' => array(
					'key' => 'layout_full_width_with_three_column',
					'name' => 'full_width_with_three_column',
					'label' => 'Full width with three column',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_accordion' => array(
					'key' => 'layout_accordion',
					'name' => 'accordion',
					'label' => 'Accordion',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_case_study_display_section' => array(
					'key' => 'layout_case_study_display_section',
					'name' => 'case_study_display_section',
					'label' => 'Case study display section',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_testimonial_full_width_slider' => array(
					'key' => 'layout_testimonial_full_width_slider',
					'name' => 'testimonial_full_width_slider',
					'label' => 'Testimonial full width slider',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_bottom_cta_banner' => array(
					'key' => 'layout_bottom_cta_banner',
					'name' => 'bottom_cta_banner',
					'label' => 'Bottom CTA banner',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_image_and_text' => array(
					'key' => 'layout_image_and_text',
					'name' => 'image_and_text',
					'label' => 'Image and text',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_row_gradient' => array(
					'key' => 'layout_row_gradient',
					'name' => 'row_gradient',
					'label' => 'Row gradient',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_section_title_bar' => array(
					'key' => 'layout_section_title_bar',
					'name' => 'section_title_bar',
					'label' => 'Section title bar',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_case_study_hub' => array(
					'key' => 'layout_case_study_hub',
					'name' => 'case_study_hub',
					'label' => 'Case study hub',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_hero_banner_bottom_bar' => array(
					'key' => 'layout_hero_banner_bottom_bar',
					'name' => 'hero_banner_bottom_bar',
					'label' => 'Hero banner bottom bar',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_case_study_single_post_layout' => array(
					'key' => 'layout_case_study_single_post_layout',
					'name' => 'case_study_single_post_layout',
					'label' => 'Case study single post layout',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Add Section',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-flexible-content.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );
} );

